# Generated by Django 4.1.5 on 2023-02-15 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fluxo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor_desc', models.CharField(max_length=100, unique=True, verbose_name='Setor')),
            ],
        ),
        migrations.CreateModel(
            name='Verba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_verba', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Lançamento')),
                ('valor_verba', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor da Verba')),
                ('desc_verba', models.CharField(max_length=200, verbose_name='Descrição')),
                ('motivo_verba', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Motivo')),
                ('setor_verba', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fluxo.setor', verbose_name='Setor')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solic', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Solicitação')),
                ('desc_solic', models.CharField(max_length=100, verbose_name='Descrição do pedido')),
                ('motivo_solic', models.TextField(help_text='Escreva detalhes da solicitação', max_length=1000, verbose_name='Motivo do pedido')),
                ('valor_solic', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor Solicitado')),
                ('anexos', models.FileField(blank=True, null=True, upload_to=fluxo.models.anexar_em)),
                ('data_aprov', models.DateTimeField(blank=True, null=True, verbose_name='Aprovação Diretoria')),
                ('motivo_aprov', models.TextField(blank=True, help_text='Escreva detalhes da devolutiva', max_length=1000, verbose_name='Motivo Aprovação')),
                ('valor_aprov', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Valor Aprovado')),
                ('data_fin', models.DateTimeField(blank=True, null=True, verbose_name='Liberação Financeiro')),
                ('motivo_fin', models.TextField(blank=True, help_text='Escreva detalhes da devolutiva', max_length=1000, verbose_name='Motivo Financeiro')),
                ('data_fis', models.DateTimeField(blank=True, null=True, verbose_name='Liberação Fiscal')),
                ('motivo_fis', models.TextField(blank=True, help_text='Escreva detalhes da devolutiva', max_length=1000, null=True, verbose_name='Motivo Fiscal')),
                ('etapa_oc', models.CharField(choices=[('1', 'Solicitação'), ('2', 'Aprovação'), ('3', 'Fiscal'), ('4', 'Financeiro'), ('9', 'Finalizada')], max_length=50, verbose_name='Etapa')),
                ('status_oc', models.CharField(choices=[('ABE', 'Aberta'), ('ANL', 'Análise'), ('LIB', 'Liberada'), ('NEG', 'Negada'), ('CAN', 'Cancelada')], max_length=50, verbose_name='Status')),
                ('data_fim_oc', models.DateTimeField(blank=True, null=True, verbose_name='Data Encerramento')),
                ('setor_oc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fluxo.setor', verbose_name='Setor')),
                ('usuario_log', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
