# Generated by Django 4.1.5 on 2023-02-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocompra',
            name='etapa_oc',
            field=models.CharField(choices=[('1', 'Solicitação'), ('2', 'Aprovação'), ('3', 'Fiscal'), ('4', 'Financeiro'), ('9', 'Finalizada')], default='1', max_length=50, verbose_name='Etapa'),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='status_oc',
            field=models.CharField(choices=[('ABE', 'Aberta'), ('ANL', 'Análise'), ('LIB', 'Liberada'), ('NEG', 'Negada'), ('CAN', 'Cancelada')], default='ABE', max_length=50, verbose_name='Status'),
        ),
    ]
