# Generated by Django 4.1.5 on 2023-02-20 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fluxo', '0003_setor_gestor_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='gestor_setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Gestor'),
        ),
    ]
